namespace TelemetryPlatform.Domain.Entities;

/// <summary>
/// Persisted domain entity for a sensor reading.  Separate from the hot-path
/// <see cref="TelemetryPlatform.Domain.ValueObjects.TelemetryPoint"/> struct so that ORM
/// mapping concerns (surrogate key, table column names) never pollute the memory-critical
/// value object used in the Channel pipeline.
/// </summary>
public sealed class SensorReading
{
    /// <summary>Database surrogate key (auto-generated by Postgres sequence).</summary>
    public long Id { get; set; }

    /// <summary>UTC timestamp of the reading (stored as Unix milliseconds in DB).</summary>
    public long TimestampMs { get; set; }

    /// <summary>Numeric sensor identifier.</summary>
    public short SensorId { get; set; }

    /// <summary>Sensor value in its native engineering unit.</summary>
    public double Value { get; set; }

    /// <summary>Flag bits from the original TelemetryPoint.</summary>
    public short Flags { get; set; }

    /// <summary>Component type tag for partitioning (e.g., "hydraulic_pump", "fuel_regulator", "landing_gear").</summary>
    public string ComponentType { get; set; } = string.Empty;

    /// <summary>Session/test-run identifier for grouping batch inserts.</summary>
    public Guid SessionId { get; set; }
}
